- name: apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Install pymysql driver
  ansible.builtin.apt:
    name: python3-pymysql
    state: present